1884761: Candlepin presents a different number of certificates for a consumer based on accept header (ENT-3127)
candlepin/candlepin pull request #2827
Opened 2020-10-20 11:53 UTC by wolfdale

Changes 
- Exporting content access certs for a consumer along with entitlement certs

Pending 
- Test cases

2020-10-23 07:24 UTC, Januson requested changes
Changes look good. I have a few suggestions regarding the exporter and its tests.

2020-10-23 10:38 UTC, wolfdale commented on server/src/main/java/org/candlepin/sync/Exporter.java
> +            exportContentAccessCerts(baseDir, consumer);
Added a unit test for it.

2020-10-23 10:38 UTC, wolfdale commented on server/src/main/java/org/candlepin/sync/Exporter.java
> +        ContentAccessCertExporter contentAccessCertExporter) {
Yes agreed.

2020-10-23 10:38 UTC, wolfdale commented on server/src/main/java/org/candlepin/sync/ContentAccessCertExporter.java
> +public class ContentAccessCertExporter {
Sure, moved all the writer logic inside new certificate exporter class.

2020-10-23 10:38 UTC, wolfdale commented on server/src/main/java/org/candlepin/sync/Exporter.java
> +                try {
Changed.

2020-10-26 08:19 UTC, Januson approved these changes

2020-10-26 08:19 UTC, merged