ENT-2594: Mechanism to determine if SCA can be enabled for a consumer
candlepin/candlepin pull request #2829
Opened 2020-10-22 09:44 UTC by Januson

- Add a new endpoint GET /consumers/{consumer_uuid}/content_access
 - Add a new endpoint GET /owners/{owner_key}/content_access

2020-10-28 18:41 UTC, jturel commented
hey @Januson is there any way you can get us a scratch build to test this change against in Katello? Our plan is to code to the API, and handle the HTTP 404 case appropriately. The idea being that once this reaches Hosted it will start working in the way we intend to use it.

2020-10-29 17:29 UTC, Ceiu requested changes
I feel like the logic here could live in the ContentAccessManager instead of adding another class for handling business logic. And, oddly, there's not really business logic here -- it's just a matter of fetching the consumer or owner object, and then building a DTO to return following the rules outlined in the design doc.

Following the current Candlepin design, this type of thing should live entirely in the resource layer, and then when we have a service layer for the owner and consumer endpoints, that moves there (though we still have some details to work out like who handles translation to and from DTOs, etc.)

A lot of this can be boiled down to two very tiny resource methods:

For owner content access:
```
    public ContentAccessDTO getContentAccess(@PathParam("owner_key") @Verify(Owner.class) String key) {
        Owner owner = this.findOwnerByKey(key);

        String caMode = Util.firstOf(
            owner.getContentAccessMode(),
            ContentAccessMode.getDefault().toDatabaseValue());

        String caList = Util.firstOf(
            owner.getContentAccessModeList(),
            ContentAccessMode.getDefault().toDatabaseValue());

        return new ContentAccessDTO()
            .setContentAccessMode(caMode)
            .setContentAccessModeList(caList);
    }
```

and for consumers:

```
    public ContentAccessDTO getContentAccess(@PathParam("consumer_uuid") @Verify(Consumer.class) String uuid) {
        Consumer consumer = consumerCurator.verifyAndLookupConsumer(uuid);

        String caMode = Util.firstOf(
            consumer.getContentAccessMode(),
            consumer.getOwner().getContentAccessMode(),
            ContentAccessMode.getDefault().toDatabaseValue());

        String caList = Util.firstOf(
            consumer.getOwner().getContentAccessModeList(),
            ContentAccessMode.getDefault().toDatabaseValue());

        return new ContentAccessDTO()
            .setContentAccessMode(caMode)
            .setContentAccessModeList(caList);
    }
```

Where ```Util.firstOf``` is defined as:

```
    public static String firstOf(String... values) {
        for (T value : values) {
            if (value != null && !value.isEmpty()) {
                return value;
            }
        }

        return null;
    }
```

These could be further shrunk, optimized, and made slightly more generic around what we need with a bit of work. But mostly they use pre-existing validation steps (even if the Consumer resolver/validator is in the wrong spot itself), and minimizes the overall work needed. 

This is almost purely API-level logic, so I'm not sure we need to get fancier than necessary here.

2020-10-29 17:29 UTC, Ceiu commented on server/src/main/java/org/candlepin/controller/ContentAccessService.java
> +public class ContentAccessService {
I feel like the logic here could live in the ContentAccessManager instead of adding another class for handling business logic.

2020-11-12 20:19 UTC, Ceiu commented
The only remaining issue I have is a non-blocking issue that we can correct later if it comes up. acking.

2020-11-12 20:20 UTC, Ceiu approved these changes

2020-11-12 20:20 UTC, Ceiu commented on server/src/main/java/org/candlepin/controller/OwnerContentAccess.java
> +        return "OwnerContentAccess{" +
For these, we should follow the format we use in the other objects: ClassName [prop=value, prop2=value2, ...]

2020-11-12 20:20 UTC, merged