change default content access mode list when in hosted mode
candlepin/candlepin pull request #2980
Opened 2021-03-22 18:30 UTC by jdhrh

This satisfies a requirement of the upcoming opt-in for hosted customers to simple content access mode.

2021-03-23 13:52 UTC, jdhrh commented
Looking at this spec test. I'm assuming my local config is different since it doesn't fail locally.

2021-03-23 13:59 UTC, nikosmoum commented
@jdhrh Yes, you have to deploy candlepin in Hosted mode with the appropriate flags (`server/bin/deploy -Ha`). Certain tests only run on one mode and not on the other, or they behave differently depending on the mode.

2021-03-23 14:01 UTC, jdhrh commented
Additionally while in here. Is it a bug that standalone can set the contentAccessModeList but not the contentAccessMode despite the exception saying it shouldn't be able to set either? The check and throw does not exist currently on the contentAccessMode configuration logic today but the exception states `"The owner content access mode and content access mode list cannot be set " +
                        "directly in standalone mode."`

2021-03-23 14:09 UTC, nikosmoum commented
The message we return is not reflective of the actual code, but the intention is still accurate, that someone using standalone mode _shouldn't_ be changing the content access mode list (even though they can) [See](https://github.com/candlepin/candlepin/blob/f3e39f15be9dabd729005818605abb627aae64f1/server/src/main/java/org/candlepin/resource/OwnerResource.java#L920-L922), so I think we can leave it as is.

There are future plans to remove all SCA restrictions in standalone mode anyway.

2021-03-24 11:03 UTC, nikosmoum commented
Adding in progress label since we'll need to clarify the larger SCA changes needed with a design first

2021-04-07 12:20 UTC, nikosmoum requested changes
While this will work for creating an Owner with the new default modeList, there's a few other places where the `ContentAccessManager.ContentAccessMode.getDefault()` method is used to check what we consider the default contentAccessModeList to be, that also need to be changed, in order for logic else where to work:
- `OwnerResource.getOwnerContentAccess()`
- 2 places in `OwnerResource.validateContentAccessModeChanges()`
- `ConsumerResource.getContentAccessForConsumer()`
- `Owner.contentAccessModeList` (default variable initialization)
- `ContentAccessManager.resolveContentAccessValue()` : This utility method seems to be used for resolving both the mode and the modeList, so my initial reaction would be to continue using it as is for wherever the mode is being resolved, but introduce a new method (e.g. `resolveContentAccessListValue`) for the places it's called from that need to resolve the modeList.

Now, applying the same change you did here to all these places is tedious and not good design. Given that throughout the system until now we've considered 'entitlement' to be the default for both mode and modeList, and now that's changed, I say we need a new method called something like `ContentAccessManager.ContentAccessMode.getListDefaultDatabaseValue()` that will return 'entitlement,org_environment' and can be used in all the places mentioned above. It returns the db value (string) because all those places I mention do call that right after they fetch the enum value. (Note: other places, that need to fetch the mode default will continue using `ContentAccessManager.ContentAccessMode.getDefault()`).

@Ceiu Do you have any better ideas here? (Keep in mind this PR need to go in ASAP, and anything that needs more thinking/design time will need to be relegated to later)

2021-04-07 14:59 UTC, Ceiu commented
@nikosmoum @jdhrh 
While I understand the immediate need here, I also have a very strong desire to not have to deal with maintaining wonky behavior or more partial features with the SCA feature. It's been kind of a pain doing any maintenance on this feature as basically every aspect of it has gone in with a "we need it now" imperative.

That said, I think the gist of what you've outlined should work here. The change I would make is that since the default-fetching function would be returning a string, it doesn't belong on the ContentAccessMode enum, but rather on the ContentAccessManager -- something like ```ContentAccessManager.getDefaultContentAccessModeList()``` as a static function. That would serve as the drop-in replacement for all of the places called out in your comment.

As a side note, I would argue that the initializer values in owner should move to assignments in the constructor, as mixing those is kind of bad practice, and I personally find the former to be somewhat annoying.

2021-04-08 11:16 UTC, nikosmoum commented
@jdhrh Also one more thing: this PR is for master. Once it's reviewed & merged you'll want to port the same change to candlepin-3.2-HOTIFX, since that is the y-stream you're using in Hosted right now (so the priority really is to get it to candlepin-3.2-HOTFIX).

2021-04-08 14:08 UTC, Ceiu commented
ok to test

2021-04-08 14:14 UTC, jdhrh commented on server/src/main/java/org/candlepin/resource/OwnerResource.java
> +        if (config.getBoolean(ConfigProperties.STANDALONE)) {
Updated with this change.

2021-04-09 10:15 UTC, nikosmoum requested changes
A couple of minor changes and this should be good to merge

2021-04-09 13:27 UTC, jdhrh commented on server/src/main/java/org/candlepin/controller/ContentAccessManager.java
> +    private String resolveContentAccessListValue(String value, boolean resolveNull) {
Javadocs added. Please let me know if they are sufficient.

2021-04-09 13:30 UTC, Ceiu commented on server/src/main/java/org/candlepin/controller/ContentAccessManager.java
> +        public static String getListDefaultDatabaseValue() {
This should exist on ContentAccessManager, not the ContentAccessMode enum.

2021-04-09 13:50 UTC, nikosmoum commented on server/src/main/java/org/candlepin/controller/ContentAccessManager.java
> +    private String resolveContentAccessListValue(String value, boolean resolveNull) {
ack

2021-04-12 09:22 UTC, merged

2021-04-12 09:23 UTC, nikosmoum commented
@jdhrh Let's port this to candlepin-3.1-HOTIFX

2021-04-12 17:23 UTC, Ceiu reviewed
ack