Use logger in create_test_repo.py script
candlepin/candlepin pull request #3025
Opened 2021-05-04 08:35 UTC by jirihnidek

* Logger is already used in new test_data_import.py script. Thus
  it make sense to use same approach for create_test_repo.py
  script too.
* Added Python package deploy_pkg to be able to share code
  between these too Python scripts
* Fixed few minor issues in both scripts
* format() method is used in create_test_repo.py

2021-05-04 13:06 UTC, Ceiu requested changes
Looks good, just need a new line at the end of the logger.py file.

Couple notes:
- If you didn't already know, the logger's various log messages support the C-style printf formatting natively. You can swap the print statements to use it fairly painlessly by changing the '%' separator to a comma and letting the logger handle it from there. I.e. ```print(' Creating symbolic link %s' % symlink_name)``` becomes ```log.info(' Creating symbolic link %s', symlink_name)```
- The name of the deploy_pkg module may change to something more generic as more things end up using that and we convert more of our utilities to python (probably something like util_pkg). Not critical here for this PR, but just an FYI for future updates.
-

2021-05-10 11:37 UTC, jirihnidek commented on server/bin/deploy_pkg/logger.py
> +    return logger
Good point. Updated.

2021-05-10 11:41 UTC, jirihnidek commented
> Looks good, just need a new line at the end of the logger.py file.

Thanks for review.

> Couple notes:
> 
>     * If you didn't already know, the logger's various log messages support the C-style printf formatting natively. You can swap the print statements to use it fairly painlessly by changing the '%' separator to a comma and letting the logger handle it from there. I.e. `print(' Creating symbolic link %s' % symlink_name)` becomes `log.info(' Creating symbolic link %s', symlink_name)`

Yeah I know. I prefer to use `format()` methods, because it will be easy to convert it to f-strings in the future.

>     * The name of the deploy_pkg module may change to something more generic as more things end up using that and we convert more of our utilities to python (probably something like util_pkg). Not critical here for this PR, but just an FYI for future updates.

It would be fine. If the code would be used in the future for some other purpose, then I'm not against renaming `deploy_pkg` to something like `util_pkg`.

2021-05-10 13:31 UTC, Ceiu approved these changes

2021-05-10 13:32 UTC, merged