Updated Vagrantfile and Ansible playbooks for general use
candlepin/candlepin pull request #3229
Opened 2022-02-17 20:37 UTC by Ceiu

- Updated the Candlepin Vagrantfile and candlepin.yml playbooks
  to be more compatible with manual invocation on arbitrary
  systems
- Renamed the "vagrant" directory to "ansible" to better align
  with its contents

2022-02-22 16:33 UTC, Ceiu commented on ansible/candlepin.yml
> +        - debug:
Ugh, this doesn't work as intended. Updating accordingly.

2022-02-22 19:01 UTC, Ceiu commented on ansible/candlepin.yml
> +        - debug:
Fixed... kind of.

2022-02-24 10:30 UTC, nikosmoum requested changes
There are some references to the `vagrant/` directory in the README, that need updating to `ansible/`

2022-02-24 13:40 UTC, Ceiu commented
@nikosmoum fixed

2022-02-24 13:50 UTC, nikosmoum approved these changes

2022-02-24 17:18 UTC, Ceiu commented
The periodic failure of the ConsumerResource test and the SonarQube failures have no barring on the changes here. I will address the former in a separate PR because I'm sick of seeing it, and I believe others are already addressing the SonarQube issues.

2022-02-24 17:57 UTC, merged