ENT-4790: Limit compliance recalculations
candlepin/candlepin pull request #3249
Opened 2022-03-08 14:09 UTC by Januson

2022-03-08 16:47 UTC, Ceiu approved these changes
Code changes seem fine, though I would like someone who went over the design to give this a once-over as well.

2022-03-09 09:11 UTC, nikosmoum requested changes
2 minor changes, but other than that this is great

2022-03-09 09:11 UTC, nikosmoum commented on src/main/java/org/candlepin/resource/ConsumerResource.java
> +        return !Objects.equals(ComplianceFacts.filter(updated.getFacts()), ComplianceFacts.of(toUpdate));
It's a bit unclear reading this that the `filter` and `of` methods are basically doing the same thing.
We could make the interface of that class a bit better by adding an overloaded `of(ConsumerDTO)` method, and make the `filter` method private.

2022-03-09 09:11 UTC, nikosmoum commented on src/main/java/org/candlepin/policy/js/compliance/hash/ComplianceFacts.java
> +        return filter(target.getFacts());
let's check if target is null first

2022-03-09 09:46 UTC, nikosmoum commented
also there are some non-flaky test failures though that seem affected by the changes

2022-03-09 13:13 UTC, nikosmoum requested changes

2022-03-10 09:37 UTC, Januson commented on src/main/java/org/candlepin/resource/ConsumerResource.java
> +        if (complianceChangesMade) {
Updates without any compliance/syspurpose changes are ~20% faster.

2022-03-10 09:39 UTC, Januson commented on src/main/java/org/candlepin/resource/ConsumerResource.java
> +        boolean complianceChangesMade = complianceFactsChanged || installedProductsChanged;
Done.

2022-03-10 12:18 UTC, merged