[M] Updated several dependencies to their latest available versions (ENT-4808)
candlepin/candlepin pull request #3281
Opened 2022-03-31 15:22 UTC by Ceiu

2022-03-31 17:44 UTC, JoshAlbrecht23 approved these changes

2022-04-01 12:28 UTC, nikosmoum approved these changes
Change looks fine, but checkstyle has a weird error

2022-04-01 13:08 UTC, nikosmoum requested changes
Actually just remembered we have the other build.gradle files to update too.
Shouldn't be too much of a problem (and if any is, we can create separate tasks)

2022-04-04 08:35 UTC, nikosmoum commented
ack

2022-04-04 08:35 UTC, merged