2070159: Update resource locator annotation warnings
candlepin/candlepin pull request #3316
Opened 2022-04-22 17:35 UTC by wottop

Checks the interfaces for the Resource classes
Downgraded log warning to info for PUT/POST with no @Consumes as this
 is the expected state

2022-04-26 15:00 UTC, JoshAlbrecht23 commented
These changes look good to me, but I'd like to get a second opinion!

2022-04-26 15:52 UTC, Januson requested changes
Changes look good, but it looks like they introduced a NPE.

2022-04-26 15:52 UTC, Januson commented on src/main/java/org/candlepin/resteasy/ResourceLocatorMap.java
> +            if (!m.isAnnotationPresent(Consumes.class) &&
Tests are hitting NPE at line 255. I guess we have to seach for the interface annotation as well.

2022-04-26 15:52 UTC, Januson commented on src/main/java/org/candlepin/resteasy/ResourceLocatorMap.java
> +            if (!m.isAnnotationPresent(Produces.class) &&
Could you add some tests? We don't have any for this class.

2022-04-28 08:46 UTC, Januson approved these changes

2022-04-28 08:46 UTC, merged