Update openapi jars [ENT-5076]
candlepin/candlepin pull request #3428
Opened 2022-06-21 18:03 UTC by wottop

Used 2 commits so that the update from the new openapi version would be separate from our additions.

2022-06-22 07:36 UTC, nikosmoum requested changes

2022-06-22 07:41 UTC, nikosmoum commented on buildSrc/src/main/java/org/openapitools/codegen/languages/AbstractJavaJAXRSServerCodegen.java
> -public abstract class AbstractJavaJAXRSServerCodegen extends AbstractJavaCodegen implements BeanValidationFeatures {
And now that I think about it, we also need to do the same for each of the .mustache template files we're overriding (api.mustache, formParams.mustache, pojo.mustache, returnTypeInterface.mustache). We're basically rebasing our custom changes on them to the 6.0.0 versions from here: https://github.com/OpenAPITools/openapi-generator/tree/6.0.x/modules/openapi-generator/src/main/resources/JavaJaxRS/spec

2022-06-24 11:24 UTC, nikosmoum commented
Unsure if it's the exact same issue, but it may be this one: https://github.com/OpenAPITools/openapi-generator/issues/12549

2022-06-24 11:24 UTC, nikosmoum commented
Also, can we get the commit message to include the upgraded version (6.0.0)?

2022-06-27 15:56 UTC, wottop commented
The pojo.mustache file was added to the client because of bugs in the implementation of 6.0.0

2022-06-28 08:15 UTC, nikosmoum commented
As a note for the future: Whenever the fix for https://github.com/OpenAPITools/openapi-generator/issues/12549 is available in a version we can upgrade to, we should remove the pojo.mustache template workaround.

2022-06-28 08:17 UTC, nikosmoum requested changes
Can we squash this and also make the commit message more specific e.g. 'Upgrade to openapi-generator 6.0.0' which helps searching the git log

2022-06-28 13:27 UTC, nikosmoum approved these changes

2022-06-28 14:35 UTC, merged