Convert entitlement_resource_spec test to Java (ENT-5200)
candlepin/candlepin pull request #3505
Opened 2022-08-05 18:42 UTC by wottop

Changed use of the KeyValueParamDTO because it violates the spec generation

2022-08-08 16:39 UTC, Januson requested changes
Overall the changes look good. I am just a bit worried about the amount of sleeps used in the tests. We should address that otherwise it will lead to poor spec test performance.

2022-08-08 16:39 UTC, Januson commented on spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceSpecTest.java
> +        sleep(15000);
Why do we need such long pauses compared to Ruby? Shouldn't join() handle the waiting?

2022-08-09 18:38 UTC, wottop commented on spec-tests/src/test/java/org/candlepin/spec/entitlements/EntitlementResourceSpecTest.java
> +        List<Pair> data = List.of(new Pair("system", "5"),
I made a list of map entries because they have a non-unique key field.

2022-08-22 15:27 UTC, Januson approved these changes

2022-08-22 16:48 UTC, merged