[M] Removed setting encoding on FileConfiguration implementation (ENT-5322)
candlepin/candlepin pull request #3511
Opened 2022-08-15 14:20 UTC by Ceiu

- Removed the getEncoding and setEncoding methods from
  FileConfiguration and all implementation classes, as it could
  not be applied in all cases, and could be lost or desync'd in
  some cases
- Added new methods to FileConfiguration for specifying the
  character encoding during config load

2022-08-15 14:21 UTC, Ceiu commented
This will need to be backported to 4.0 and 4.1 upon acceptance.

2022-08-15 15:01 UTC, JoshAlbrecht23 requested changes
The changes look good, but I had a question on some assertions on a couple tests.

2022-08-15 16:35 UTC, Ceiu commented on src/test/java/org/candlepin/config/PropertiesFileConfigurationTest.java
> +        assertNotEquals(new String("Mötley Crüe".getBytes(UTF_8), US_ASCII), config.getString("glam.band"));
So the intent here is to re-encode a string we know has unicode characters into ASCII so we can have the mangled string available to use as comparison. Providing UTF-8 for the second param during string creation would re-create the original string, effectively being a very long no-op, and would be equivalent to the assertion above it.

The previous version of the test intended to work this way, but called the no-param variant of `getBytes()`, which uses the system default charset. This is fine in cases where the system default was UTF-8, as it was for us up until about two weeks ago, but fails in cases where the default anything else.

2022-08-15 17:27 UTC, JoshAlbrecht23 commented on src/test/java/org/candlepin/config/PropertiesFileConfigurationTest.java
> +        assertNotEquals(new String("Mötley Crüe".getBytes(UTF_8), US_ASCII), config.getString("glam.band"));
Okay, that makes sense! I appreciate the explanation.

2022-08-15 17:28 UTC, JoshAlbrecht23 approved these changes

2022-08-16 12:26 UTC, wottop requested changes

2022-08-16 12:26 UTC, wottop commented on src/main/java/org/candlepin/config/PropertiesFileConfiguration.java
> +    // instance backing this fascade.
"facade"

2022-08-16 13:54 UTC, merged