Made logback.xml a config file to prevent overwriting
candlepin/candlepin pull request #3541
Opened 2022-08-29 14:11 UTC by JoshAlbrecht23

I was unable to test these changes as the `tito build --rpm --test --verbose` command is not working for me.

The error that I was running into when attempting to run the tito command:
```
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.swWspV
+ umask 022
+ cd /tmp/tito/rpmbuild-candlepinxisoscm9/BUILD
+ cd /tmp/tito/rpmbuild-candlepinxisoscm9/BUILD
+ rm -rf candlepin-4.2.7
+ /usr/bin/gzip -dc /tmp/tito/rpmbuild-candlepinxisoscm9/SOURCES/candlepin-4.2.7-complete.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd candlepin-4.2.7
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ pathfix.py -pni '/usr/bin/python3 -s' bin/scripts/code/setup/cpdb bin/scripts/code/setup/cpsetup
usage: pathfix.py [-h] [--config CONFIG] path
pathfix.py: error: unrecognized arguments: -pni bin/scripts/code/setup/cpdb bin/scripts/code/setup/cpsetup
error: Bad exit status from /var/tmp/rpm-tmp.swWspV (%prep)

RPM build warnings:
    line 23: It's not recommended to have unversioned Obsoletes: Obsoletes: candlepin-tomcat
    line 24: It's not recommended to have unversioned Obsoletes: Obsoletes: candlepin-tomcat6
    line 25: It's not recommended to have unversioned Obsoletes: Obsoletes: candlepin-devel
    line 26: It's not recommended to have unversioned Obsoletes: Obsoletes: candlepin-certgen-lib
    line 23: It's not recommended to have unversioned Obsoletes: Obsoletes: candlepin-tomcat
    line 24: It's not recommended to have unversioned Obsoletes: Obsoletes: candlepin-tomcat6
    line 25: It's not recommended to have unversioned Obsoletes: Obsoletes: candlepin-devel
    line 26: It's not recommended to have unversioned Obsoletes: Obsoletes: candlepin-certgen-lib

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.swWspV (%prep)

```

2022-08-29 19:03 UTC, Ceiu requested changes
The change itself looks fine, but the commit formatting and PR title formatting need to be updated:

- The commit addresses a specific BZ, so it should follow the syntax: `BZ#: commit title`
- The PR title doesn't indicate the Jira number nor the branch tag

2022-08-29 20:24 UTC, Ceiu approved these changes

2022-08-29 20:25 UTC, Ceiu commented
Looks good to me (and seems simple enough), but it would probably be a good idea to have someone more familiar with the RPM spec bits to confirm. @nikosmoum perhaps?

2022-08-30 11:58 UTC, nikosmoum requested changes

2022-08-30 11:58 UTC, nikosmoum commented on candlepin.spec.tmpl
> +%config(noreplace) %{_sharedstatedir}/tomcat/webapps/%{name}/WEB_INF/classes/logback.xml
I tried building the rpm with tito but it fails with `File not found: /tmp/tito/rpmbuild-candlepinvn3f8h5p/BUILDROOT/candlepin-4.2.7-1.x86_64/var/lib/tomcat/webapps/candlepin/WEB_INF/classes/logback.xml`
I think `WEB_INF` is supposed to be `WEB-INF`

2022-08-30 12:15 UTC, nikosmoum commented on candlepin.spec.tmpl
> +%config(noreplace) %{_sharedstatedir}/tomcat/webapps/%{name}/WEB_INF/classes/logback.xml
Aside from this, the change does the job: an rpm upgrade that includes changes to the logback.xml results in a new file being created without overriding the old one: `warning: /var/lib/tomcat/webapps/candlepin/WEB-INF/classes/logback.xml created as /var/lib/tomcat/webapps/candlepin/WEB-INF/classes/logback.xml.rpmnew`

2022-08-30 12:18 UTC, nikosmoum commented
And one more thing change the BZ id to the candlepin BZ (`2112308`) which is what we are using in our commits. `1787456` is the satellite BZ id which we don't use in commits

2022-08-30 14:04 UTC, nikosmoum approved these changes

2022-08-30 14:26 UTC, merged