Migrate hypervisor_check_in to Java part 2
candlepin/candlepin pull request #3615
Opened 2022-10-06 14:43 UTC by wottop

Includes cleanup to part 1

2022-10-07 14:17 UTC, JoshAlbrecht23 requested changes

2022-10-07 14:17 UTC, JoshAlbrecht23 commented on spec-tests/src/test/java/org/candlepin/spec/HypervisorCheckInSpecTest.java
> +        rh00271Cert = null;
You shouldn't need to assign to null since the are already being reassigned to the output of the stream filtering in the next couple of lines

2022-10-12 14:52 UTC, nikosmoum commented on spec-tests/src/test/java/org/candlepin/spec/HypervisorCheckInSpecTest.java
> +        userClient = ApiClients.trustedUser(user.getUsername());
Can we replace all `ApiClients.trustedUser(username)` with `ApiClients.basic(username, password)` through out this PR (and for all other spec tests from now on)? The ApiClients.trustedUser and ApiClients.trustedConsumer should never be used in spec tests (aside from the few tests that explicitly test those authentication methods, e.g. TrustedConsumerAuthSpecTest & TrustedUserAuthSpecTest).

2022-10-18 13:29 UTC, JoshAlbrecht23 approved these changes

2022-10-20 17:20 UTC, merged