[M] Eliminate trustedConsumer/trustedUser usage in spec tests
candlepin/candlepin pull request #3624
Opened 2022-10-12 14:41 UTC by nikosmoum

- While porting spec tests from ruby to java, there has been a heavy use of ApiClients.trustedConsumer and ApiClients.trustedUser auth methods which are using the 'magic' headers (cp-consumer/cp-user). The ruby tests never used those, and instead use the identity cert + key and username + password for authentication. This change switches all existing java spec tests to use the ApiClients.basic(username, password) and ApiClients.ssl(consumer) which are the more realistic authentication use cases.

2022-10-12 14:43 UTC, nikosmoum commented
Note for developers:
When porting tests, here are the equivalent authentication methods to use for each ruby method:
```
# Ruby => Java
Candlepin.new(username, password) or user_client() => ApiClients.basic(username, password)

Candlepin.new('admin', 'admin') => ApiClients.admin()

Candlepin.new(nil, nil, cert, key) or consumer_client() => ApiClients.ssl(consumerDTO)

Candlepin.new => ApiClients.noAuth()
```

2022-10-12 15:17 UTC, Ceiu commented
Changes look good to me, but we should add some documentation on each of those methods in `ApiClients` so this doesn't happen again in the future. Especially since once this PR is merged, that comment is going to get buried.

2022-10-12 17:27 UTC, Ceiu requested changes
Changes look good to me, but we should add some documentation on each of those methods in `ApiClients` so this doesn't happen again in the future. Especially since once this PR is merged, that comment is going to get buried.

2022-10-13 14:29 UTC, nikosmoum commented
@Ceiu Done, also I've renamed the cloud auth client into bearer token client since that is more accurate

2022-10-13 16:00 UTC, merged