[M] Reverted product/content link from activation key and environments (ENT-5504)
candlepin/candlepin pull request #3664
Opened 2022-11-08 14:48 UTC by Ceiu

- ActivationKey no longer references products directly, instead referencing products by Red Hat product ID
- Environment no longer references content directly, instead referencing content by Red Hat content ID
- Removed the ActivationKey and Environment entity remapping logic from org refresh and product/content update flows
- Internal entity model API improvements, cleanup, and changes
- Removed some long-unused code

2022-11-08 14:51 UTC, Ceiu commented
This is the first part of the changes to perform mapping resolution in the case where a mapping error is detected during refresh and import. This PR focuses on removing the churn around environments and activation keys and reverting the product and content references back to RHIDs from strict UUID references. Due to the critical nature of this change, a lot of attention should be paid to the operations surrounding environment content and activation key product usage.

Additionally, this PR focuses on updating the model APIs a bit to encourage using ID references rather than objects, while still permitting pulling children objects as necessary (specifically the owner from activation key or environment). This is less critical for Candlepin behavior, but should help make object manipulation cleaner and easier to maintain.

2022-11-15 16:28 UTC, wottop commented
Looks like an issue here:

org.candlepin.spec.OwnerProductResourceSpecTest shouldAllowDeletingAProductAssociatedWithAnActivationKey() FAILED



  org.candlepin.invoker.client.ApiException: Message: Internal Server Error

  HTTP response code: 500

  HTTP response body: {

    "displayMessage" : "Runtime Error could not execute statement at org.mariadb.jdbc.export.ExceptionFactory.createException:282",

    "requestUuid" : "10f36dac-e1da-45a4-81d8-f55ea05fcca4"

  }

  HTTP response headers: {connection=[close], content-type=[application/json], date=[Tue, 15 Nov 2022 15:07:43 GMT], server=[Apache-Coyote/1.1], transfer-encoding=[chunked], vary=[Accept-Encoding], x-candlepin-request-uuid=[10f36dac-e1da-45a4-81d8-f55ea05fcca4], x-version=[4.2.10-1, 4.2.10-1]}

      at app//org.candlepin.spec.OwnerProductResourceSpecTest.shouldAllowDeletingAProductAssociatedWithAnActivationKey(OwnerProductResourceSpecTest.java:648)

2022-11-15 19:10 UTC, JoshAlbrecht23 requested changes
Looks good, just had some small comments.

2022-11-15 20:45 UTC, Ceiu commented on src/test/java/org/candlepin/controller/PoolManagerTest.java
> +        // test where we were sending the wrong product IDs in, and still got the correct result.
The offending tests that I spotted were already fixed as part of this PR, so the TODO is referring to the general approach/usage of mocks.

We can add a card if one doesn't already exist, but I fear it'll be doomed to stay in the backlog for all eternity.

2022-11-15 20:48 UTC, Ceiu commented on src/main/java/org/candlepin/model/OwnerProductCurator.java
> +                "WHERE akp.key_id = :key_id AND product_id = :product_id";
I'll have to run through the query planner again to double check, but IIRC, due to how Hibernate caches all the individual queries until it does a flush, it ended up being faster to do them individually like that.

2022-11-15 21:07 UTC, Ceiu commented on src/main/java/org/candlepin/model/OwnerProductCurator.java
> +                "WHERE akp.key_id = :key_id AND product_id = :product_id";
nm, I was mistaken. Fixed.

2022-11-17 14:47 UTC, JoshAlbrecht23 approved these changes

2022-11-18 16:43 UTC, Ceiu commented
Rebased; and removed the very short-lived environment-content lookups and checks from the OrphanCleanupJob and ContentCurator.

2022-11-28 18:41 UTC, wottop commented
lgtm.

2022-11-28 18:43 UTC, merged