Migrate virt_spec to Java
candlepin/candlepin pull request #3680
Opened 2022-11-16 13:56 UTC by Januson

2022-11-25 15:23 UTC, nikosmoum requested changes
A few minor issues but otherwise good

2022-11-25 15:23 UTC, nikosmoum commented on spec-tests/src/test/java/org/candlepin/spec/VirtSpecTest.java
> +            .updateEntitlement(entitlement.get(0).get("id").asText(), toUpdate(entitlement));
shouldn't this be reducing the quantity from 3 to 2? `toUpdate` it seems to just pass the original entitlement's quantity (3)

2022-11-28 14:08 UTC, Januson commented on spec-tests/src/test/java/org/candlepin/spec/VirtSpecTest.java
> +            .hasSize(1)
Done. I forgot to remove it after refactoring it below. There should be only one entitlement. There is one that covers both products. The second entitlement in the original test was caused by global setup in virt_helper.

2022-11-28 14:09 UTC, Januson commented on spec-tests/src/test/java/org/candlepin/spec/VirtSpecTest.java
> +    public void shouldLoseEntitlementWhenGuestStopsAndIsRestartedElsewhere() {
Done. I missed a piece during migration.

2022-11-28 14:38 UTC, nikosmoum requested changes

2022-11-28 14:38 UTC, nikosmoum commented on spec-tests/src/test/java/org/candlepin/spec/VirtSpecTest.java
> +//        hostClient.guestIds().updateGuests(host.getUuid(), guestIds);
accidentally left over?

2022-11-28 14:38 UTC, nikosmoum commented on spec-tests/src/test/java/org/candlepin/spec/VirtSpecTest.java
> +        linkHostToGuests(hostClient, host, GUEST_UUID);
this should probably be `unlinkHostsGuests`

2022-11-28 15:57 UTC, Januson commented on spec-tests/src/test/java/org/candlepin/spec/VirtSpecTest.java
> +//        hostClient.guestIds().updateGuests(host.getUuid(), guestIds);
Done.

2022-11-29 08:17 UTC, merged