CANDLEPIN-117: Migrate derived_product_spec to Java
candlepin/candlepin pull request #3701
Opened 2022-12-01 20:05 UTC by wottop

2022-12-19 15:16 UTC, Januson requested changes
Changes look good. I have just a few suggestions.

2023-01-03 20:58 UTC, wottop commented on spec-tests/src/test/java/org/candlepin/spec/entitlements/DerivedProductSpecTest.java
> +        assertTrue(found);
problem: 
product.get("content"))
returns a single JsonArray. The size will always be 1. singleElement on it returns the array not a member.

2023-01-04 19:15 UTC, wottop commented on spec-tests/src/test/java/org/candlepin/spec/entitlements/DerivedProductSpecTest.java
> +        assertTrue(found);
I think I found a way around it. It needed some help in converting.

2023-01-06 12:23 UTC, Januson approved these changes

2023-01-06 15:31 UTC, merged