CANDLEPIN-254: Migrate consumer_resource_content_spec to Java
candlepin/candlepin pull request #3728
Opened 2023-01-06 09:42 UTC by Januson

2023-01-06 15:06 UTC, JoshAlbrecht23 requested changes
Looks good! Just a couple minor changes

2023-01-06 15:06 UTC, JoshAlbrecht23 commented on spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceContentSpecTest.java
> +            .containsOnly("some_other_value");
You can do the following as a replacement and only use two lines:
```
assertConsumerOverrides(consumerClient, consumer)
  .singleElement()
  .returns("some_other_value", ContentOverrideDTO::getValue);
```

2023-01-09 12:20 UTC, Januson commented on spec-tests/src/test/java/org/candlepin/spec/consumers/ConsumerResourceContentSpecTest.java
> +            List.of(createOverride("TESt-FIELD", "some_other_value")));
Done.

2023-01-09 14:37 UTC, JoshAlbrecht23 approved these changes

2023-01-09 19:17 UTC, merged