CANDLEPIN-270: Migrate person_consumer_spec, domain_consumer_spec and deleted_consumer_spec to Java
candlepin/candlepin pull request #3732
Opened 2023-01-06 17:04 UTC by Januson

2023-01-10 21:13 UTC, JoshAlbrecht23 requested changes
Looks good! Just had a spot with an extra new line.

2023-01-10 21:13 UTC, JoshAlbrecht23 commented on spec-tests/src/test/java/org/candlepin/spec/consumers/DomainConsumerSpecTest.java
> +
Extra new line

2023-01-11 10:47 UTC, Januson commented on spec-tests/src/test/java/org/candlepin/spec/consumers/DomainConsumerSpecTest.java
> +
Done.

2023-01-11 14:46 UTC, JoshAlbrecht23 approved these changes

2023-01-11 14:46 UTC, merged