CANDLEPIN-179: Migrate sku_level_enable_override_spec to Java
candlepin/candlepin pull request #3733
Opened 2023-01-06 21:34 UTC by wottop

2023-01-09 12:52 UTC, Januson requested changes
Changes look good. I have just a few suggestions.

2023-01-09 12:52 UTC, Januson commented on spec-tests/src/test/java/org/candlepin/spec/content/SkuLevelEnableOverrideSpecTest.java
> +            "1.3.6.1.4.1.2312.9.2." + content1.getId() + ".1.8");
There is a custom assertion that simplifies work with certs.

```java
assertThatCert(X509Cert.fromEnt(ent))
    .hasContentRepoEnabled(content1);
```
`fromEnt` currently accepts only JsonNode so you'll need to add an overloaded version.

2023-01-09 16:48 UTC, wottop commented on spec-tests/src/test/java/org/candlepin/spec/content/SkuLevelEnableOverrideSpecTest.java
> +        assertThat(!consumer.getEnvironments().isEmpty());
what is the typo? is there a better assertThat for "the collection is not empty"?

2023-01-09 18:36 UTC, Januson commented on spec-tests/src/test/java/org/candlepin/spec/content/SkuLevelEnableOverrideSpecTest.java
> +        assertThat(!consumer.getEnvironments().isEmpty());
Parentheses. `isEmpty()` should be at the end so that it's not called on the environments but as the assert.

2023-01-10 12:31 UTC, Januson approved these changes

2023-01-10 12:31 UTC, merged