[M] CANDLEPIN-455: Normalized consumer fact constants and usage
candlepin/candlepin pull request #3758
Opened 2023-01-23 16:45 UTC by Ceiu

- Updated the Consumer.Facts pseudo-class to contain all of the facts Candlepin uses either directly or indirectly
- Updated the CloudProfileFacts to reference Consumer.Facts rather than hard-coding its own copies of the values
- Updated several places in Candlepin code which were using hard-coded strings for facts to use the new values in Consumer.Facts

2023-01-24 18:35 UTC, wottop requested changes
Just the one line

2023-01-24 18:35 UTC, wottop commented on src/main/java/org/candlepin/model/CloudProfileFacts.java
> + * The facts in this enum come from the consumer facts, and are primarily used to determine whethr
typo

2023-01-24 21:01 UTC, Ceiu commented on src/main/java/org/candlepin/model/CloudProfileFacts.java
> + * The facts in this enum come from the consumer facts, and are primarily used to determine whethr
Fixed

2023-01-25 17:34 UTC, wottop approved these changes

2023-01-25 17:34 UTC, merged