CANDLEPIN-497: Remove Ruby setup from container scripts
candlepin/candlepin pull request #3862
Opened 2023-02-22 17:30 UTC by wottop

2023-02-23 10:07 UTC, nikosmoum requested changes
ACK on the removal of ruby from ansible scripts
NACK on its removal from the containers. We still need them there to run rspec on older supported branches.

2023-02-23 10:07 UTC, nikosmoum commented on docker/candlepin-base-cs8/setup-devel-env.sh
> -# Setup and install rvm, ruby and pals
We can't remove ruby from our c7 and cs8 containers. We need it to run rspec in older branches.

2023-02-23 10:07 UTC, nikosmoum commented on ansible/roles/candlepin/README.md
> -This role depends on the `rvm1.ruby` role for installing and configuring RVM. At the time of writing, Candlpin
we also need to remove the reference of the role from `ansible/requirements.yml`

2023-02-28 08:57 UTC, nikosmoum commented
@wottop If the changes in the pastebin need are needed (copying of the Gemfiles), should they not be applied on this PR?

2023-02-28 13:07 UTC, wottop commented
> @wottop If the changes in the pastebin need are needed (copying of the Gemfiles), should they not be applied on this PR?

That is the workaround for the fact that a local build will retrieve the master branch to build the image.

2023-02-28 14:52 UTC, nikosmoum approved these changes

2023-02-28 14:52 UTC, merged