CANDLEPIN-512: Update org_migrator for schema changes
candlepin/candlepin pull request #3878
Opened 2023-03-01 20:32 UTC by wottop

2023-03-03 14:09 UTC, Ceiu requested changes

2023-03-03 14:09 UTC, Ceiu commented on bin/scripts/org_migrator/org_migrator.py
> +            'SELECT ec.content_id FROM cp_environment_content ec JOIN cp_environment e on e.id = ec.environment_id WHERE e.owner_id = %s'
This chunk here is for pulling all content UUIDs to ensure we have all the referenced content. With the env content no longer being a hard ref to a specific content instance, we no longer need this query here.

2023-03-03 14:09 UTC, Ceiu commented on bin/scripts/org_migrator/org_migrator.py
> +        'SELECT akp.product_id FROM cp_activation_key ak JOIN cp_activation_key_products akp ON akp.key_id = ak.id WHERE ak.owner_id = %s'
Like the content lookup, this is to ensure we have all the referenced products by UUID. Injecting product IDs into the mix won't work. This needs to be removed, and, potentially, changed to a lookup that fetches the product by its ID instead.

2023-03-03 19:55 UTC, wottop commented
In going back over this I noticed something about how we are collecting the uuids for products.

Pulling product uuids from the cp_pool table adds them to the collection if they are not already in the cp2_owner_products table. This will complete the connection in the destination db, correct?

It appears that the original queries were also achieving the same outcome, so I duplicated it here.

My question now is, are we trying to replicate the data AND fix it on the fly?

2023-03-04 11:25 UTC, Ceiu requested changes

2023-03-04 11:25 UTC, Ceiu commented on bin/scripts/org_migrator/org_migrator.py
> +            'SELECT cont.uuid FROM cp_environment e JOIN cp_environment_content ec ON e.id = ec.environment_id  ' + \
We still don't want to do this query at all anymore -- It's no longer required for pulling the data, and this query doesn't guarantee it'll pull the same thing on every export.

Same with the product version

2023-03-04 11:30 UTC, Ceiu commented
> In going back over this I noticed something about how we are collecting the uuids for products.

> Pulling product uuids from the cp_pool table adds them to the collection if they are not already in the cp2_owner_products table. This will complete the connection in the destination db, correct?

It will not. It simply pulls the product row that is referenced. It does not add an additional row in cp2_owner_products (or cp2_owner_content). This is required for two reasons: first and foremost, in the event we had an environment or activation key pointing to an out-of-org product or content, that we'll be able to import the org dump without needing to explicitly track down which org, if any, owns it and export them as well. Secondly, in the case of an operation misbehaving, we want to be sure we pull the exact data a given org is working with so we can reproduce any issues.

> It appears that the original queries were also achieving the same outcome, so I duplicated it here.

> My question now is, are we trying to replicate the data AND fix it on the fly?

The org migrator should not be performing any manipulation of the data at all, nor should it be fixing anything it sees. It simply exports the data as it exists -- no matter how broken it may be -- so it can be imported locally for reproduction.

The original queries were fetching the product and content references off environments and activation keys because they had to. Referential integrity forced those explicit references to exist. Now that we've reverted back to soft references via ID, we no longer need the product to be pulled if it hasn't been already.

2023-03-17 15:06 UTC, Ceiu commented on bin/scripts/org_migrator/org_migrator.py
> +        #   - cp_activation_key_products.product_id
This comment line is obsolete, and no longer needed

2023-03-20 15:32 UTC, merged