[M] CANDLEPIN-253: Remove obsolete Maven/Mead code from candlepin
candlepin/candlepin pull request #4232
Opened 2023-09-12 08:44 UTC by bakajstep

- Remove maven

2023-09-12 18:00 UTC, wottop commented
Removals remaining:

MEAD-HOWTO.md
mead.chain
in build.gradle, do we still need the MavenPublication stuff?
in releasers.conf, should we delete the DistGitMeadReleaser?

2023-09-14 11:43 UTC, bakajstep commented
> Removals remaining:
> 
> MEAD-HOWTO.md mead.chain in build.gradle, do we still need the MavenPublication stuff? in releasers.conf, should we delete the DistGitMeadReleaser?

Done, releasers.conf we do not need at all but MavenPublication we still need.

2023-09-14 13:15 UTC, nikosmoum requested changes
We still need to delete mead.chain and MEAD-HOWTO.md

2023-09-14 15:04 UTC, nikosmoum approved these changes

2023-09-14 15:10 UTC, merged