[F] Add CloudAccountOrgSetupJob org mismatch case exception
candlepin/candlepin pull request #4345
Opened 2023-11-07 11:40 UTC by nikosmoum

- Defines adapter interface exception in case the cloud account setup cannot be done yet due to an org key conflict upstream of Candlepin.

2023-11-07 12:10 UTC, nikosmoum commented
Note on sonar code coverage failure: lets ignore it because it's because of the new exception class

2023-11-07 20:24 UTC, JoshAlbrecht23 requested changes
Looks good! I just noticed an extra new line

2023-11-07 20:24 UTC, JoshAlbrecht23 commented on src/test/java/org/candlepin/async/tasks/CloudAccountOrgSetupJobTest.java
> +
Extra new line

2023-11-08 11:05 UTC, nikosmoum commented on src/test/java/org/candlepin/async/tasks/CloudAccountOrgSetupJobTest.java
> +
updated

2023-11-08 13:43 UTC, JoshAlbrecht23 approved these changes

2023-11-08 13:44 UTC, merged