CANDLEPIN-740: Updated RH packaged certificate
candlepin/candlepin pull request #4424
Opened 2023-12-11 21:44 UTC by joshmalbrecht

- updated the certificate to be the same as the one in main

I was able to verify the changes by creating an export from the stage environment and successfully importing the manifest using the `/owners/<owner-key>/imports/async` endpoint

2023-12-11 21:53 UTC, Ceiu requested changes
Few minor changes and one important one:
- the missing new line at the end of the new cert
- missing line break in the commit message between the title and the body
- gencerts needs to be updated to no longer reference the r2-ca.crt file

2023-12-11 21:53 UTC, Ceiu commented on config/candlepin/candlepin-redhat-ca.crt
> +-----END CERTIFICATE-----
The trailing line break got lost in the update; we'll want to restore that for CLI output friendliness.

2023-12-12 16:05 UTC, nikosmoum reviewed
based on testing, this change shouldn't be needed. lets wait for a clear reproduction of the issue, to find the root cause

2023-12-15 17:40 UTC, joshmalbrecht commented
Closing, as the issue appears to be that the customer's upstream dir was moved and the certificates could not be found.

2023-12-15 17:40 UTC, closed without merging