[M] CANDLEPIN-758: Update/add foreign keys around cp_anonymous_certificates
candlepin/candlepin pull request #4463
Opened 2024-01-02 16:12 UTC by nikosmoum

- Update the foreign key from cp_anonymous_cloud_consumers to cp_anonymous_certificates to not be CASCADE on delete, and make sure the CertificateCleanupJob unlinks those consumers before deleting their certs to avoid this constraint.
- Add missing foreign key from cp_anonymous_certificates to cp_cert_serial.

2024-01-03 15:25 UTC, joshmalbrecht requested changes
Looks good! I just noticed an extra new line to remove.

2024-01-03 15:25 UTC, joshmalbrecht commented on src/test/java/org/candlepin/async/tasks/CertificateCleanupJobTest.java
> +        assertThat(this.anonymousCloudConsumerCurator.getByUuid(consumerWithExpiredCert.getUuid()))
Extra new line

2024-01-04 13:21 UTC, nikosmoum commented on src/test/java/org/candlepin/async/tasks/CertificateCleanupJobTest.java
> +        assertThat(this.anonymousCloudConsumerCurator.getByUuid(consumerWithExpiredCert.getUuid()))
done

2024-01-04 13:30 UTC, joshmalbrecht approved these changes

2024-01-04 13:56 UTC, merged