CP-169: Removed CP Query from Activation Key
candlepin/candlepin pull request #4546
Opened 2024-02-07 16:08 UTC by wottop

- ActivationKeyResource
- ActivationKeyCurator
- ConsumerResource
- OwnerResource
- ContentOverrideCurator

2024-02-15 16:27 UTC, Ceiu requested changes

2024-02-15 16:27 UTC, Ceiu commented on src/main/java/org/candlepin/resource/ActivationKeyResource.java
> +        return overrides.stream().map(this.translator.getStreamMapper(
Let's drop the `.map` call down a line so the line breaks occur more naturally on individual operations.

(note this applies several times throughout this PR)

2024-02-15 16:27 UTC, Ceiu commented on src/main/java/org/candlepin/resource/OwnerResource.java
> +    public Iterable<ActivationKeyDTO> ownerActivationKeys(
Just return the stream directly instead of recollecting it.

(note this applies several times throughout this PR)

2024-02-15 16:27 UTC, Ceiu commented on src/test/java/org/candlepin/resource/OwnerResourceTest.java
> +        Iterable<ActivationKeyDTO> keys = result;
What are we getting out of this redeclaration?

2024-02-15 16:27 UTC, Ceiu commented on src/main/java/org/candlepin/model/activationkeys/ActivationKeyCurator.java
> +    public List<ActivationKey> listAllActivationKeys() {
Do we need this method with the global `.listAll`?

2024-02-15 16:32 UTC, wottop commented
My apologies. I rebased on the AHC change, ut didn't make the changes suggested on my other PR. Going too quickly at EOD.

2024-02-19 17:46 UTC, Ceiu approved these changes

2024-02-20 13:59 UTC, merged