CANDLEPIN-796: Create ueber certificate generator
candlepin/candlepin pull request #4570
Opened 2024-02-20 14:35 UTC by Januson

- Add x509 certificate builder
- Add Ueber certificate generator

2024-02-26 20:34 UTC, joshmalbrecht approved these changes
Looks good to me! I'll add a tag to get an additional set of eyes on this

2024-02-26 20:34 UTC, joshmalbrecht commented on src/main/java/org/candlepin/pki/certs/UeberCertificateGenerator.java
>              // December 1, 2049 at 13:00 GMT
Nit: This comment should be UTC and not GMT

2024-02-28 13:52 UTC, nikosmoum requested changes
2 minor requests and this is ready

2024-02-28 13:52 UTC, nikosmoum commented on src/main/java/org/candlepin/pki/certs/X509CertificateBuilder.java
> +        GeneralName subject = new GeneralName(GeneralName.directoryName, distinguishedName.value());
Can we keep the implementation comment from BouncyCastlePKIUtility regarding subject alt names here? it provides details/rationale for why we're doing this, and referencing standards/RFC documents. I think this is the kind of knowledge we need to preserve

2024-02-28 13:52 UTC, nikosmoum commented on src/main/java/org/candlepin/pki/certs/UeberCertificateGenerator.java
> +            throw new BadRequestException(i18n.tr(
Can we add back the log.error before throwing this? It is useful to have the details/stacktrace of why exactly the cert generation failed in the logs. If we only throw an HTTP-level exception then that would be lost

2024-02-28 16:30 UTC, nikosmoum approved these changes

2024-02-28 16:40 UTC, merged