CANDLEPIN-150: Add pagination to getHypervisors endpoint
candlepin/candlepin pull request #4607
Opened 2024-03-11 08:27 UTC by Januson

- Added paging params to getHypervisors endpoint spec
- Added pagination for getting hypervisors by owner
- Added pagination for getting hypervisors by ids
- Removed unused code from consumer curator

2024-03-12 16:10 UTC, joshmalbrecht requested changes
Just noticed a change to use the ConfigProperties.MAX_PAGING_SIZE configuration

2024-03-13 13:37 UTC, Januson commented on src/main/java/org/candlepin/resource/OwnerResource.java
> +    private static final int MAX_RESULTS = 1000;
Done.

2024-03-13 14:48 UTC, joshmalbrecht requested changes
Just one small change to remove a temporary variable

2024-03-13 14:48 UTC, joshmalbrecht commented on src/main/java/org/candlepin/model/ConsumerCurator.java
> +        return lowerCaseHypervisorIds;
No need to for the `lowerCaseHypervisorIds` variable, we can just return the list:

```
    private static List<String> toLowerCase(Collection<String> hypervisorIds) {
        return hypervisorIds.stream()
            .distinct()
            .map(String::toLowerCase)
            .sorted()
            .toList();
    }
```

2024-03-13 14:53 UTC, joshmalbrecht approved these changes

2024-03-13 15:40 UTC, merged