CANDLEPIN-147: Added paging to GET /owners endpoint
candlepin/candlepin pull request #4629
Opened 2024-03-19 20:19 UTC by wottop

2024-03-21 20:45 UTC, joshmalbrecht requested changes
Noticed some easy to fix changes

2024-03-21 20:45 UTC, joshmalbrecht commented on src/main/java/org/candlepin/model/OwnerCurator.java
> +
Extra new line

2024-03-21 20:45 UTC, joshmalbrecht commented on spec-tests/src/test/java/org/candlepin/spec/owners/OwnerResourceSpecTest.java
> +                .isLessThanOrEqualTo(0);
We can use `isNotPostive()` instead of `isLessThanOrEqualTo(0)`

2024-03-21 20:45 UTC, joshmalbrecht commented on src/test/java/org/candlepin/model/OwnerCuratorTest.java
> +        assertIterableEquals(ownerCurator.listAll(args), List.of(owner1, owner3));
Flip the arguments around `assertIterableEquals(expected, actual)`.

It looks like this happens in other tests as well, so we will want to update those as well

2024-03-21 20:45 UTC, joshmalbrecht commented on src/main/java/org/candlepin/model/OwnerCurator.java
> +        if (order != null && order.size() > 0) {
Instead of `order.size()  > 0` we can do `!order.isEmpty()`

2024-03-22 16:02 UTC, nikosmoum approved these changes

2024-03-22 16:04 UTC, merged