CANDLEPIN-734: Added paging to GET /products endpoint
candlepin/candlepin pull request #4632
Opened 2024-03-20 21:17 UTC by wottop

- Created new method in ProductCurator listAll with ProductQueryArguments
- Updated ProductResource method getProducts to take paging parameters and call the new curator method
- Updated candlepin-api-spec.yaml to include the paging parameters

2024-03-21 20:31 UTC, joshmalbrecht requested changes
Noticed some small and easy to fix changes

2024-03-21 20:31 UTC, joshmalbrecht commented on spec-tests/src/test/java/org/candlepin/spec/products/ProductResourceSpecTest.java
> +
Extra new line

2024-03-21 20:31 UTC, joshmalbrecht commented on src/test/java/org/candlepin/model/ProductCuratorTest.java
> +        assertEquals(page.get(3).getId(), "test_product-6");
Flip the arguments around so it is `assertEquals(expected, actual)`

2024-03-21 20:31 UTC, joshmalbrecht commented on spec-tests/src/test/java/org/candlepin/spec/products/ProductResourceSpecTest.java
> +                .isLessThanOrEqualTo(0);
Instead of using `isLessThanOrEqualTo(0)` we can use `isNotPositive()`

2024-03-21 20:31 UTC, joshmalbrecht commented on src/main/java/org/candlepin/model/ProductCurator.java
> +     * @return a count of owners
Update this Java doc to be for Products instead of Owners

2024-03-22 16:14 UTC, nikosmoum approved these changes
Looks good to me, once the items that @joshmalbrecht pointed out are fixed

2024-03-22 17:34 UTC, joshmalbrecht approved these changes

2024-03-22 19:01 UTC, merged