[M] CANDLEPIN-846: Make sure anonymous orgs are marked as such
candlepin/candlepin pull request #4653
Opened 2024-04-03 15:11 UTC by nikosmoum

- In case an org already exists in Candlepin before the CloudAccountOrgSetupJob gets to create it, it should instead make sure to set it as anonymous, if it should be marked as such.

2024-04-03 21:30 UTC, Ceiu requested changes
Potentially fine, but I have a question regarding the record definition

2024-04-04 10:57 UTC, nikosmoum commented on src/main/java/org/candlepin/service/model/CloudAccountData.java
> +        if (isAnonymous == null) {
updated!

2024-04-04 13:06 UTC, Ceiu approved these changes

2024-04-04 13:08 UTC, Ceiu commented
Looks like one of the spec tests are failing in hosted mode

2024-04-04 14:59 UTC, nikosmoum commented
this is a weird failure. it doesn't seem related to my change at all, and I can't reproduce it locally, but somehow it failed on both hosted setups

2024-04-05 12:39 UTC, joshmalbrecht approved these changes

2024-04-05 12:39 UTC, merged