[M] CANDLEPIN-821: Updated OwnerInfoCurator to stop using Hibernate APIs
candlepin/candlepin pull request #4712
Opened 2024-05-16 15:54 UTC by Ceiu

- Updated OwnerInfoCurator to stop using Hibernate APIs, such as Hibernate criteria and Hibernate implementations of JPA interfaces
- Flagged all of the "secure criteria" methods in AbstractHibernateCurator as deprecated

2024-05-21 19:14 UTC, joshmalbrecht requested changes
Looks good! I just noticed a small issue in one of the java docs

2024-05-21 19:19 UTC, Ceiu commented on src/main/java/org/candlepin/model/OwnerInfoCurator.java
> +     * query, and root. Note that the predicate is build using a correlated subquery matching the
done

2024-05-21 19:25 UTC, joshmalbrecht approved these changes

2024-05-22 10:30 UTC, nikosmoum approved these changes

2024-05-22 10:30 UTC, merged