[M] CANDLEPIN-856: Support environment deletion without deleting consumers
candlepin/candlepin pull request #4724
Opened 2024-05-30 14:53 UTC by bakajstep

- If an environment was deleted, any consumers in the environment that did not belong to any other environment were also deleted. For console.redhat.com content templates, we did not want this behavior. With deleteConsumers set to false, we left the consumers environment-less.

2024-05-30 14:54 UTC, bakajstep commented on src/main/java/org/candlepin/resource/EnvironmentResource.java
> +            Map<Boolean, List<Consumer>> partitionedConsumers = consumers.stream()
With this approach we should save time because we won't have to go through the list twice but only once.

2024-05-30 17:09 UTC, Ceiu requested changes
Looks pretty good, just need to ensure we don't NPE since our boolean flag is an object and not a primitive.

Some minor grammar improvements can also be made since there are other things to address as well.

2024-05-30 17:09 UTC, Ceiu commented on spec-tests/src/test/java/org/candlepin/spec/environments/EnvironmentSpecTest.java
> +    public void shouldNotDeleteConsumerWithDeletingHisLastEnvironment() {
nit (grammar): "shouldNotDeleteConsumerWhenDeletingItsLastEnvironment"

2024-05-31 13:22 UTC, bakajstep commented on src/test/java/org/candlepin/resource/EnvironmentResourceTest.java
> +    void shouldConsumersBeRemovedFromEnvironmentButNotDeletedWhenDeleteConsumersIsFalse() {
done

2024-05-31 13:22 UTC, bakajstep commented on spec-tests/src/test/java/org/candlepin/spec/environments/EnvironmentSpecTest.java
> +    public void shouldNotDeleteConsumerWithDeletingHisLastEnvironment() {
done

2024-05-31 13:44 UTC, Ceiu approved these changes

2024-05-31 13:45 UTC, merged