[M] CANDLEPIN-871: Added CS8 container to CI
candlepin/candlepin pull request #4759
Opened 2024-07-02 08:49 UTC by bakajstep

2024-07-03 20:56 UTC, joshmalbrecht requested changes
I just noticed an extra new line in the new containerfile.

I'm also wondering if this containerfile should live in `.github/containers` as it seems that this containerfile is to only be used for spec tests that use the Postgres database.

2024-07-03 20:56 UTC, joshmalbrecht commented on containers/cs8.Containerfile
> +
Extra new line

2024-07-04 09:01 UTC, bakajstep commented on containers/cs8.Containerfile
> +
done

2024-07-04 09:05 UTC, bakajstep commented
> I just noticed an extra new line in the new containerfile.
> 
> I'm also wondering if this containerfile should live in `.github/containers` as it seems that this containerfile is to only be used for spec tests that use the Postgres database.

Thats a good question. I was thinking about that too. We can have containers on one place in `containers` folder or have one in `containers` and other in `.github/containers`, but then we would have `Containerfiles` for CI on two diffrent places. Maybe @nikosmoum what dou you think about that?

2024-07-04 09:46 UTC, nikosmoum commented
I think moving the cs8 containerfile to `.github/containers` make sense, since the main `/containers` directory is for containers that end up in shippable images (to quay). So it makes sens to keep them in separate places

2024-07-04 09:50 UTC, bakajstep commented
Moved to `./.github/containers/`

2024-07-08 13:11 UTC, joshmalbrecht approved these changes

2024-07-08 13:12 UTC, merged