[M] Updated logic for offering id in ConsumerCloudData
candlepin/candlepin pull request #4860
Opened 2024-09-25 12:44 UTC by bakajstep

- Refactored the ConsumerCloudData class to include a `setCloudOfferingIds` method, enabling direct replacement of cloud offering IDs instead of only appending them via `addCloudOfferingIds`. This allows for flexible management of cloud offering IDs, with validation ensuring that the maximum length is not exceeded.

2024-09-25 21:37 UTC, Ceiu requested changes

2024-09-25 21:37 UTC, Ceiu commented on src/main/java/org/candlepin/model/ConsumerCloudData.java
> +        String joinedCloudOfferingIds = String.join(",", cloudOfferingIds);
Need null checks

2024-09-25 21:37 UTC, Ceiu commented on src/main/java/org/candlepin/model/ConsumerCloudData.java
> +        this.setCloudOfferingIds(Arrays.asList(cloudOfferingIds));
null check here

2024-09-25 21:37 UTC, Ceiu commented on src/test/java/org/candlepin/model/ConsumerCloudDataTest.java
> +    public void testAddCloudOfferingIds() {
Let's split this up into distinct tests for the expected cases (single, multiple for both the array and collection input), and then our null, empty, and malformed cases.

2024-09-25 21:44 UTC, Ceiu commented
We should also be commenting these methods to be much clearer on how they function. What happens when a null collection is provided? How about a null element within that collection? The documentation needs to be very clear on what is expected to happen such that unshared expectations don't cause problems in the future.

Additionally, public methods in an abstraction or application boundary need to be air tight. They shouldn't be triggering exceptions that they aren't explicitly throwing themselves as a function of violating those aforementioned expectations.

2024-09-26 08:28 UTC, bakajstep commented on src/main/java/org/candlepin/model/ConsumerCloudData.java
> +        String joinedCloudOfferingIds = String.join(",", cloudOfferingIds);
done

2024-09-26 08:28 UTC, bakajstep commented on src/main/java/org/candlepin/model/ConsumerCloudData.java
> +        this.setCloudOfferingIds(Arrays.asList(cloudOfferingIds));
done

2024-09-26 08:32 UTC, bakajstep commented
> We should also be commenting these methods to be much clearer on how they function. What happens when a null collection is provided? How about a null element within that collection? The documentation needs to be very clear on what is expected to happen such that unshared expectations don't cause problems in the future.
> 
> Additionally, public methods in an abstraction or application boundary need to be air tight. They shouldn't be triggering exceptions that they aren't explicitly throwing themselves as a function of violating those aforementioned expectations.

I hope they are better documented. I just don't know if I shouldn't change it everywhere and rewrite the tests to be separate?

2024-09-27 13:54 UTC, Ceiu requested changes
One last whitespace change and this is good.

2024-09-27 13:54 UTC, Ceiu commented on src/main/java/org/candlepin/model/ConsumerCloudData.java
> +        for (String cloudOfferingId : cloudOfferingIds) {
Let's add line breaks between each of these blocks so it's clear each is separate from the others.

2024-10-04 13:47 UTC, Ceiu approved these changes

2024-10-04 13:47 UTC, merged