[M] CANDLEPIN-938: Updated query space declarations for native SQL queries
candlepin/candlepin pull request #4909
Opened 2024-11-05 18:43 UTC by Ceiu

- Updated the way query spaces are declared for all native queries to use the table names and/or entity classes as appropriate
- Updated all query space declarations to use the Hibernate API rather than the JPA query hint

2024-11-05 18:54 UTC, Ceiu commented
This one's a bit squirrely in that with our model, sometimes we want to specify the entity, sometimes we want to specify the table name, and sometimes we want both. Which is correct depends on exactly what tables need to be updated. The docs heavily imply that specifying an entity by class will get all of its tables [1], but [element] collections *will not* always be caught when doing so and must be specified separately as if they are an entirely disconnected entity. For cases where our joins or collections are represented in the object model with entities, we can use those (ProductContent, for example); but if such an entity class is not available, we must specify the table.

There are other options we could do here to avoid specifying the tables directly -- i.e. we could define the query spaces as constants somewhere, and then for every collection or table that would need to be specified explicitly, reference the constant instead -- but I feel like these have the potential for even more desync and maintenance mistakes and don't fundamentally address the core issue of the entity itself not really "owning" its collections in practice.

Also, this change is *entirely* contrary to virtually every example or article I could find for using query hints. Everyone seems to be specifying the entity's FQCN (or list of) as the value; but apparently the table name is what should have been used all along. 

[1] "Add all query spaces associated with the entity with the given type.
Same as addSynchronizedQuerySpace(java.lang.String) for all tables mapped by the given entity."

https://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/query/SynchronizeableQuery.html#addSynchronizedEntityClass(java.lang.Class)

2024-11-05 19:08 UTC, Ceiu commented
Something to consider as this is reviewed: is there a common rule we can establish for these declarations that's not too heavy handed that could be applied here? I'm seeing some inconsistencies within the changes already, so I'm all for getting such a thing established straight away.

2024-11-05 21:06 UTC, joshmalbrecht requested changes
Noticed some small changes and had a question

2024-11-05 21:06 UTC, joshmalbrecht commented on src/main/java/org/candlepin/model/EntitlementCurator.java
> +
We can remove as this is not being used

2024-11-05 21:09 UTC, Ceiu commented on src/main/java/org/candlepin/model/ProductQueryBuilder.java
> +        List<String> querySpaces = new ArrayList<>();
Sure, done.

2024-11-05 21:10 UTC, Ceiu commented on src/main/java/org/candlepin/model/PoolCurator.java
> +
removed

2024-11-05 21:11 UTC, Ceiu commented on src/main/java/org/candlepin/model/PoolCurator.java
> +            .addSynchronizedEntityClass(Product.class)
Agreed, fixed.

2024-11-05 21:11 UTC, Ceiu commented on src/main/java/org/candlepin/model/EntitlementCurator.java
> +
Removed

2024-11-05 21:30 UTC, joshmalbrecht approved these changes

2024-11-06 12:28 UTC, bakajstep commented
LGTM

2024-11-06 12:28 UTC, bakajstep approved these changes

2024-11-06 19:28 UTC, merged